# ==========================================
# 1. LOGIN PAGE LOCATORS
# ==========================================
AmazonLoginPage.emailInput=id:ap_email_login
AmazonLoginPage.continueButton=id:continue
AmazonLoginPage.passwordInput=id:ap_password
AmazonLoginPage.signInSubmitButton=id:signInSubmit
# ==========================================
# 2. HOME PAGE LOCATORS
# ==========================================
AmazonHomePage.searchBox = id:twotabsearchtextbox
AmazonHomePage.searchBtn = xpath://input[@value='Go']
# ==========================================
# 3. PRODUCT LISTING PAGE LOCATORS
# ==========================================
AmazonProductListingPage.productLink = xpath://span[contains(text(),'Galaxy Z Fold8')]
# ==========================================
# 4. PRODUCT DETAIL PAGE LOCATORS
# ==========================================
AmazonProductDetailPage.productTitle = xpath://*[@id="productTitle"]
AmazonProductDetailPage.productPrice = xpath://span[@class='a-size-extra-large inemi-amount']
AmazonProductDetailPage.addToCartBtn = xpath://input[@id='add-to-cart-button' and not(@type='hidden')]
AmazonProductDetailPage.addToCartBtnPlaywright = xpath://input[@id='add-to-cart-button']
AmazonProductDetailPage.cartConfirmationMessage = xpath://span[@id="submit.add-to-cart"]//input